# Based on the 'Mavam' Powerlevel9K theme
awsvault_prompt() {
    if [ ! -z "${AWS_VAULT-}" ]; then
        echo -n " ${AWS_VAULT-} ";
    fi
}

# Prompt components
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    root_indicator
    dir
    dir_writable_joined
    rbenv
    custom_awsvault
    asdf
    newline
    prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    command_execution_time
    vcs
    background_jobs_joined
    time_joined
)

# General Prompt Configuration
typeset -g POWERLEVEL9K_MODE='nerdfont-complete';
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='';
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='';
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='';
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='';

# VI-aware Prompt
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND="clear";
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND="green";
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND="red";
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_FOREGROUND="blue";
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_FOREGROUND="yellow";
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION="🅘";
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION="🅝";
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION="🅥";

# typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_LEFT_SUFFIX="❯";

# VCS Component Colors
typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_BACKGROUND="clear";
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green";
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow";
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow";

# Terminal Status Configuration Colors
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND="clear";
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND="green";
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear";
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red";

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear';
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green';

typeset -g POWERLEVEL9K_TIME_BACKGROUND="clear";
typeset -g POWERLEVEL9K_TIME_FOREGROUND="cyan";
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear';
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta';

# Path/Folder Component Colors
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND="clear";
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND="blue";
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear";
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="cyan";
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear";
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red";
typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear";
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="cyan";
typeset -g POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red";
typeset -g POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white";

# ASDF Component Configuration
POWERLEVEL9K_ASDF_BACKGROUND="clear";

# AWS Vault Component Configuration
typeset -g POWERLEVEL9K_CUSTOM_AWSVAULT="awsvault_prompt";
typeset -g POWERLEVEL9K_CUSTOM_AWSVAULT_BACKGROUND="clear";
typeset -g POWERLEVEL9K_CUSTOM_AWSVAULT_FOREGROUND="red";
typeset -g POWERLEVEL9K_CUSTOM_AWSVAULT_VISUAL_IDENTIFIER_EXPANSION='';
