#! /usr/bin/env zsh

op_setup_file="${1}";

if [ ! -f ${op_setup_file} ]; then
    echo "Could not find specified 1password setup file! (${op_setup_file})";
    echo "Exiting...";
    exit 1;
fi

open -a "$(brew info --json=v2 "1password" | jq -r '.casks[0].artifacts[0][0]')";
# TODO Is this 'sleep' necessary?
sleep 5;
open "$(cat ${op_setup_file})";
