#! /usr/bin/env zsh

op_alias="$1";
op_setup_file="$2";
op_setup_params="$(cat $op_setup_file | cut -d'?' -f2)";

# Parse a URL and extract the value for the supplied query parameter key
py_extract_param=$(cat <<-PY_EXTRACT_PARAM
from urllib.parse import parse_qs
import sys

params = parse_qs("${op_setup_params}")
param_key = sys.argv[1]

print(params[param_key][0])
PY_EXTRACT_PARAM
);

email="$(python -c "${py_extract_param}" "email")";
server="$(python -c "${py_extract_param}" "server")";
key="$(python -c "${py_extract_param}" "key")";

echo "Setting up 1password CLI for email=${email} at server=${server}";
echo -n "Enter your account password: ";
read -s password;
echo ""

echo -n "Enter your six-digit authentication code: ";
read otp;
echo "";

# Automate the `op account add` command with `expect` since the secret key
# can't be supplied through command line args.
# FIXME Move Password/OTP capture into the expect script
cat <<-EXPECT_OP_ACCOUNT_ADD | expect
spawn op account add --email ${email} --address ${server} --shorthand ${op_alias}
expect "Enter the Secret Key for *: "
send -- "${key}\r"
expect "Enter the password for *: "
send -- "${password}\r"
expect "Enter your six-digit authentication code: "
send -- "${otp}\r"
expect eof
EXPECT_OP_ACCOUNT_ADD

exit 0;
