#! /usr/bin/env zsh

which op >/dev/null || echo "'op' not found in path" ;
which trurl >/dev/null || echo "'trurl' not found in path" ;

op_setup_url="$(cat ${1})";
op_email=$(trurl --get '{query:email}' ${op_setup_url});
op_server=$(trurl --get '{query:server}' ${op_setup_url});
op_address=$(trurl --get '{host}' ${op_server});

export OP_SECRET_KEY="$(trurl --get '{query:key}' ${op_setup_url})";

op account add --email "${op_email}" --address "${op_address}";
