#! /usr/bin/env zsh

set -euf -o pipefail;
BREW_URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh";

if bin_exists brew; then
    echo "Homebrew found...Will not install homebrew";
    exit 0;
fi

echo "Installing Homebrew...";
/bin/bash -c "$(curl -fsSl $BREW_URL)";

exit 0;
