#! /usr/bin/env zsh

INSTALL_DIR=${1:$HOME};
GITHUB_DOOM_D_REPO="git@github.com:kevinziegler/doom.d.git";
GITHUB_DOOM_REPO="git@github.com:doomemacs/doom-emacs.git";

git clone "${GITHUB_DOOM_D_REPO}" "${INSTALL_DIR}/.doom.d";
git clone "${GITHUB_DOOM_REPO}" "${INSTALL_DIR}/.emacs.d";

"${INSTALL_DIR}/.emacs.d/bin/doom" install;
emacs --eval "(all-the-icons-install-fonts t)" --kill --user "${INSTALL_DIR}";
